stages:
  - build
  - test
  - release
  - deploy

variables:
  APPLICATION_NAME: food-manager
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TEST: ${CONTAINER_IMAGE}:test
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
  K8S_INGRESS_HOST: api.food.home.maximemoreillon.com

image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

build:
  stage: build
  only:
    - tags
  # tags:
  #   - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${CONTAINER_IMAGE_TEST} .
    - docker push ${CONTAINER_IMAGE_TEST}

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  only:
    - tags
  # tags:
  #   - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - >
      docker run 
      ${CONTAINER_IMAGE_TEST}
      npm run coverage

release:
  stage: release
  only:
    - tags
  # tags:
  #   - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker pull ${CONTAINER_IMAGE_TEST}

    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_LATEST}
    - docker tag ${CONTAINER_IMAGE_TEST} ${CONTAINER_IMAGE_TAGGED}

    - docker push ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  only:
    - tags
  stage: deploy
  tags:
    - dind
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s_home/kubernetes-agent:home
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
