version: "3.7"

# TODO: volumes

services:
  mongodb:
    image: mongo:4
    logging:
      driver: none
    networks:
      - food-manager

  food-manager:
    image: moreillon/food-manager
    # build: .
    environment:
      MONGODB_HOST: mongodb
      MONGODB_DB: food_manager
    networks:
      - food-manager
    

  gui:
    image: moreillon/food-manager-front
    logging:
      driver: none
    environment:
      VUE_APP_FOOD_MANAGER_API_URL: /proxy/api
    networks:
      - food-manager

  proxy:
    image: moreillon/api-proxy:v2.3.2
    ports:
      - 8080:80
    environment:
      PROXY_ROOT: http://gui
      PROXY_API: http://food-manager
    networks:
      - food-manager

networks:
  food-manager:
