apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_RESOURCE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${K8S_RESOURCE_NAME}
  template:
    metadata:
      labels:
        app: ${K8S_RESOURCE_NAME}
    spec:
      containers:
        - name: ${K8S_RESOURCE_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          envFrom:
            - secretRef:
                name: food-manager-env

---
apiVersion: v1
kind: Service
metadata:
  name: ${K8S_RESOURCE_NAME}
spec:
  type: NodePort
  selector:
    app: ${K8S_RESOURCE_NAME}
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${K8S_RESOURCE_NAME}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - ${K8S_INGRESS_HOST}
      secretName: ${K8S_RESOURCE_NAME}-tls
  rules:
    - host: ${K8S_INGRESS_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${K8S_RESOURCE_NAME}
                port:
                  number: 80
